<?php
$users = [
    [
        'email' => 'admin@gmail.com',
        'username' => 'adminxxx',
        'name' => 'Admin',
        'password' => password_hash('admin123', PASSWORD_DEFAULT),
    ],
    [
        'email' => 'tika@gmail.com',
        'username' => 'tikaiueo',
        'name' => 'Nur Atika Binti Ardi',
        'password' => password_hash('tika99', PASSWORD_DEFAULT),
        'gender' => 'Female',
        'faculty' => 'MIPA',
        'batch' => '2024',
    ],
    [
        'email' => 'iyat@gmail.com',
        'username' => 'iyat afayat',
        'name' => 'Hilmy Affayad Akbar',
        'password' => password_hash('iyat99', PASSWORD_DEFAULT),
        'gender' => 'Male',
        'faculty' => 'Farmasi',
        'batch' => '2024',
    ],
    [
        'email' => 'dafa@gmail.com',
        'username' => 'dafakaramoy',
        'name' => 'Muhammad Daffa Usman',
        'password' => password_hash('dafa99', PASSWORD_DEFAULT),
        'gender' => 'Tidak terdefinisi',
        'faculty' => 'Ekonomi dan Bisnis',
        'batch' => '2024',
    ],
    [
        'email' => 'zalfa@gmail.com',
        'username' => 'zalfaaa',
        'name' => 'Zalfa Syauqiyah Hamka',
        'password' => password_hash('zalfa99', PASSWORD_DEFAULT),
        'gender' => 'Female',
        'faculty' => 'Kehutanan',
        'batch' => '2024',
    ],
    [
        'email' => 'kal@gmail.com',
        'username' => 'kalaa',
        'name' => 'kala malam',
        'password' => password_hash('kal99', PASSWORD_DEFAULT),
        'gender' => 'Female',
        'faculty' => 'Kehutanan',
        'batch' => '2024',
    ],
];
?>
